Use proper flag semantics instead of passing around raw integers
rpm-rs/rpm pull request #69
Opened 2023-01-01 06:23 UTC by dralley

closes #52

2023-01-01 06:29 UTC, dralley commented
@drahnr I think that this line might logically unsound, because these flags are not necessarily mutually exclusive.  I'm not 100% sure.  Thoughts?

https://github.com/rpm-rs/rpm/blob/b015c277251727c57a9f662ae953b8fad077954a/src/rpm/package.rs#L455

2023-05-18 07:26 UTC, drahnr commented on src/rpm/package.rs
> +                            flags: FileFlags::from_bits(flags).expect("Unexpected rpm file flags found"),
Should be an error, since there it's within a `try_fold` anyways, `panic` seems unnecessary.

2023-05-18 07:27 UTC, drahnr requested changes
I like it, but we should avoid any panic-ing behavior in parsing packages, regardless if incoherent or not.

2023-05-18 20:10 UTC, dralley commented
FWIW, while it's still drafted I don't necessarily expect a review, still making some changes

2023-05-18 20:12 UTC, dralley commented on src/constants.rs
> +// pub const RPMFILE_PARSE_SPECIALDIR: u32	= (1 << 19),	// special %%doc
There's still some gaps missing but we can deal with it later.  I have no idea what these are actually for.

2023-05-18 20:35 UTC, dralley commented on src/rpm/package.rs
> +            .unwrap_or(DigestAlgorithm::Md5);
Change: deleted `Default` impl for DigestAlgorithm as it should probably be contextual

Change: renamed a few fields named after `sense` to `flags`

2023-05-18 20:42 UTC, merged